# Generated by Django 3.2.7 on 2021-10-12 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ottm.model_fields
import ottm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourcedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikidataQObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_qid', message='invalid Wikidata QID "%(value)s"', regex='^Q\\d+$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TranslatedObject',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('unlocalized_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20, validators=[ottm.models.lang_code_validator])),
                ('is_administrator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sourcedobject',
            name='qids',
            field=models.ManyToManyField(related_name='linked_objects', to='ottm.WikidataQObject'),
        ),
        migrations.AddField(
            model_name='sourcedobject',
            name='sources',
            field=models.ManyToManyField(related_name='objects', to='ottm.Source'),
        ),
        migrations.CreateModel(
            name='BridgeSectionStructure',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='BridgeSectionType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='BuildingMaterial',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='BuildingUsage',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='EarthworkType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='ElectricityType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='ElectrificationSystem',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='GateMaterial',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='GeometryWithNodes',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.geometry')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.geometry',),
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject', 'ottm.sourcedobject'),
        ),
        migrations.CreateModel(
            name='LengthUnit',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
                ('symbol', models.CharField(max_length=20)),
                ('to_reference_coefficient', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='MonorailTrackType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='OperatedEntity',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject', 'ottm.sourcedobject'),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject', 'ottm.sourcedobject'),
        ),
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='RailType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='SpeedUnit',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
                ('symbol', models.CharField(max_length=20)),
                ('to_reference_coefficient', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='SurfaceMaterial',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TieType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TrackInfrastructureUsage',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TrackUsage',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TractionSystem',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='TunnelSectionMaterial',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('translatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.translatedobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.translatedobject',),
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('geometrywithnodes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.geometrywithnodes')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.geometrywithnodes',),
        ),
        migrations.CreateModel(
            name='Polyline',
            fields=[
                ('geometrywithnodes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.geometrywithnodes')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.geometrywithnodes',),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('operatedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.operatedentity')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.operatedentity',),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_text', models.CharField(max_length=200, validators=[ottm.models.non_empty_text_validator])),
                ('language_code', models.CharField(max_length=20, validators=[ottm.models.lang_code_validator])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_translations', to='ottm.translatedobject')),
            ],
            options={
                'unique_together': {('object', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='OperatorTypeState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_states', to='ottm.operator')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_states', to='ottm.operatortype')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='OperatedEntityOperatorTable',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators_table', to='ottm.operatedentity')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_table', to='ottm.operator')),
            ],
            options={
                'unique_together': {('time_span', 'operator', 'entity')},
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.AddField(
            model_name='operatedentity',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_entities', to='ottm.operator'),
        ),
        migrations.AddField(
            model_name='operatedentity',
            name='operators',
            field=models.ManyToManyField(related_name='operated_entities', through='ottm.OperatedEntityOperatorTable', to='ottm.Operator'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.geometry')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'altitude')},
            },
            bases=('ottm.geometry',),
        ),
        migrations.CreateModel(
            name='GeometryWithNodesNodeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('geometry_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_table', to='ottm.geometrywithnodes')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries_table', to='ottm.node')),
            ],
            options={
                'unique_together': {('geometry_object', 'node')},
            },
        ),
        migrations.AddField(
            model_name='geometrywithnodes',
            name='nodes',
            field=models.ManyToManyField(related_name='geometries', through='ottm.GeometryWithNodesNodeTable', to='ottm.Node'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='ottm.buildingtype')),
                ('walls_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='ottm.buildingmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='TrackInfrastructure',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='TrackSection',
            fields=[
                ('polyline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polyline')),
                ('direction', models.CharField(choices=[('normal', 'Normal'), ('reverse', 'Reverse'), ('both', 'Both')], default='both', max_length=30)),
                ('track_infrastructures', models.ManyToManyField(related_name='track_sections', to='ottm.TrackInfrastructure')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polyline',),
        ),
        migrations.CreateModel(
            name='SiteObjectTable',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_table', to='ottm.geometry')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_table', to='ottm.site')),
            ],
            options={
                'unique_together': {('time_span', 'site', 'object')},
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.AddField(
            model_name='site',
            name='objects',
            field=models.ManyToManyField(related_name='sites', through='ottm.SiteObjectTable', to='ottm.Geometry'),
        ),
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='ottm.sitetype'),
        ),
        migrations.CreateModel(
            name='ConventionalTrackSection',
            fields=[
                ('tracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.tracksection')),
                ('gauges', ottm.model_fields.CommaSeparatedFloatField(blank=True, max_length=200, null=True, validators=[ottm.models.gauge_validator])),
                ('has_tyre_roll_ways', models.BooleanField(default=False)),
                ('rail_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sections', to='ottm.railtype')),
                ('tie_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sections', to='ottm.tietype')),
                ('traction_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sections', to='ottm.tractionsystem')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ottm.lengthunit')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.tracksection',),
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('surface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.surface')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.surface',),
        ),
        migrations.CreateModel(
            name='GLTTrackSection',
            fields=[
                ('tracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.tracksection')),
                ('guided', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.tracksection',),
        ),
        migrations.CreateModel(
            name='MaglevTrackSection',
            fields=[
                ('tracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.tracksection',),
        ),
        migrations.CreateModel(
            name='ManeuverStructure',
            fields=[
                ('trackinfrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.trackinfrastructure')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.trackinfrastructure',),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('surface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.surface')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.surface',),
        ),
        migrations.CreateModel(
            name='TunnelSection',
            fields=[
                ('trackinfrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.trackinfrastructure')),
                ('infrastructures', models.ManyToManyField(related_name='tunnel_sections', to='ottm.Infrastructure')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.trackinfrastructure',),
        ),
        migrations.CreateModel(
            name='VALTracksection',
            fields=[
                ('tracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.tracksection',),
        ),
        migrations.CreateModel(
            name='WallSection',
            fields=[
                ('polyline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polyline')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_sections', to='ottm.wallmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polyline',),
        ),
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('operatedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.operatedentity')),
                ('sites', models.ManyToManyField(related_name='train_lines', to='ottm.Site')),
                ('track_sections', models.ManyToManyField(related_name='train_lines', to='ottm.TrackSection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.operatedentity',),
        ),
        migrations.CreateModel(
            name='TrackUsageState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_usage_states', to='ottm.trackusage')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TrackTypeState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_type_states', to='ottm.tracktype')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TrackNumberState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('number', models.CharField(max_length=10)),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TrackMaxSpeedState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('max_speed', models.FloatField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ottm.speedunit')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_speed_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TrackInfrastructureUsageState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_states', to='ottm.trackinfrastructureusage')),
                ('track_infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_states', to='ottm.trackinfrastructure')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='SurfaceMaterialState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surface_material_states', to='ottm.surfacematerial')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_states', to='ottm.surface')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='RoadCrossingState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('road_name', models.CharField(blank=True, max_length=100, null=True, validators=[ottm.models.non_empty_text_validator])),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_crossing_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='PolygonHole',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
                ('parent_polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='ottm.polygon', validators=[ottm.models.polygon_hole_validator])),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('polyline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polyline')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='ottm.gatematerial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polyline',),
        ),
        migrations.CreateModel(
            name='ElectrificationState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('electrified', models.BooleanField()),
                ('tension', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
                ('current_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrification_states', to='ottm.electricitytype')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrification_states', to='ottm.electrificationsystem')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrification_states', to='ottm.tracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='BuildingUsageState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_states', to='ottm.buildingusage')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_states', to='ottm.building')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='BuildingHeightState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ottm.lengthunit')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='height_states', to='ottm.building')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='BuildingFloorsState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
                ('underground_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='value should be greater than 0')])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors_states', to='ottm.building')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='BridgePier',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
                ('infrastructures', models.ManyToManyField(related_name='bridge_piers', to='ottm.Infrastructure')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_piers', to='ottm.buildingmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='BridgeAbutment',
            fields=[
                ('polygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.polygon')),
                ('infrastructures', models.ManyToManyField(related_name='bridge_abutments', to='ottm.Infrastructure')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_abutments', to='ottm.buildingmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.polygon',),
        ),
        migrations.CreateModel(
            name='RailFerryRouteSection',
            fields=[
                ('conventionaltracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.conventionaltracksection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.conventionaltracksection',),
        ),
        migrations.CreateModel(
            name='TransferTable',
            fields=[
                ('maneuverstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.maneuverstructure')),
                ('has_pit', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.maneuverstructure',),
        ),
        migrations.CreateModel(
            name='Turntable',
            fields=[
                ('maneuverstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.maneuverstructure')),
                ('is_bridge', models.BooleanField()),
                ('max_rotation_angle', models.FloatField(default=360, validators=[ottm.models.angle_validator])),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.maneuverstructure',),
        ),
        migrations.CreateModel(
            name='TunnelSectionMaterialState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_states', to='ottm.tunnelsectionmaterial')),
                ('tunnel_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_states', to='ottm.tunnelsection')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='TrackCoverSection',
            fields=[
                ('trackinfrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.trackinfrastructure')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_cover_sections', to='ottm.buildingmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.trackinfrastructure',),
        ),
        migrations.CreateModel(
            name='MonorailTrackSection',
            fields=[
                ('tracksection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.tracksection')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sections', to='ottm.monorailtracktype')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.tracksection',),
        ),
        migrations.CreateModel(
            name='ManeuverStructureState',
            fields=[
                ('sourcedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.sourcedobject')),
                ('time_span', ottm.model_fields.TimeIntervalField()),
                ('moving_structure_present', models.BooleanField()),
                ('tracks_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='value should be greater than 1')])),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='ottm.maneuverstructure')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.sourcedobject',),
        ),
        migrations.CreateModel(
            name='Earthwork',
            fields=[
                ('trackinfrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.trackinfrastructure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earthworks', to='ottm.earthworktype')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.trackinfrastructure',),
        ),
        migrations.CreateModel(
            name='BridgeSection',
            fields=[
                ('trackinfrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ottm.trackinfrastructure')),
                ('infrastructures', models.ManyToManyField(related_name='bridge_sections', to='ottm.Infrastructure')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_sections', to='ottm.buildingmaterial')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_sections', to='ottm.bridgesectionstructure')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_sections', to='ottm.bridgesectiontype')),
            ],
            options={
                'abstract': False,
            },
            bases=('ottm.trackinfrastructure',),
        ),
    ]
